import { ReactNode } from 'react';
import '@/styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <header>헤더임</header>
        <main>
          <div></div>
          {children}
        </main>
      </body>
    </html>
  );
}
