import { ReactNode } from "react";
import "@/styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <header>헤더</header>
        <main>
          <div>메인</div>
          {children}
        </main>
        <footer>푸터</footer>
      </body>
    </html>
  );
}
